# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{arnotations}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Exner"]
  s.date = %q{2010-10-26}
  s.description = %q{Allows creation of Rails Applications with Topic Map Fragment support}
  s.email = %q{darkwingdex@googlemail.com}
  s.extra_rdoc_files = [
    "README.md",
    "TODO"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "TODO",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/ar_notations.rb",
    "lib/ar_notations/TOXTM2.rb",
    "lib/ar_notations/array_ext.rb",
    "lib/ar_notations/associations.rb",
    "lib/ar_notations/characteristics.rb",
    "lib/ar_notations/fragment_metadata.rb",
    "lib/ar_notations/id.rb",
    "lib/ar_notations/model_core_ext.rb",
    "lib/ar_notations/rails3_core_ext.rb",
    "lib/ar_notations/xtm2.dtd",
    "lib/ar_notations/xtm2.rng",
    "lib/ar_notations/xtm2.xsd",
    "lib/ar_notations/xtm_validation.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/DeX77/ARNotations}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Enrich your app with Topic Map fragments}
  s.test_files = [
    "spec/ar_notations/associations_spec.rb",
    "spec/ar_notations/characteristics_spec.rb",
    "spec/ar_notations/controller_core_ext_spec.rb",
    "spec/ar_notations/id_specs.rb",
    "spec/ar_notations/model_core_ext_spec.rb",
    "spec/ar_notations_spec.rb",
    "spec/ar_notations_spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
    else
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
  end
end

